### ISSUE TITLE
TypeError: 'this'

### ISSUE THREAD

**Issue by escarabelg** [Webschool-io/be-mean-instagram-nodejs-exercises#196]
### Código

> OBS: Todas as aulas de nodejs que haviam 'this' apresentaram o mesmo erro(ex: aula de _virtuals_), estou com a versão v6.1.0 do node.

``` js
'use strict';
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost/teste');

var PokemonSchema = new mongoose.Schema({
  name: String
  , description: String
  , type: String
  , attack: Number
  , defense: Number
  , height: Number
});

PokemonSchema.methods.findSimilarType = (cb) => {
  return this.model('Pokemon').find({type: this.type}, cb);
};

const PokemonModel = mongoose.model('Pokemon', PokemonSchema);
const poke = new PokemonModel({name: 'Insetoide', type: 'inseto'});

poke.findSimilarType((err, data) => {
  if(err) return console.log('ERRO: '+err);
  return data.foreach((pokemon) => console.log('Pokemon: '+pokemon));
});
```
### ERRO

```
return this.model('Pokemon').find({type: this.type}, cb);
              ^
TypeError: this.model is not a function
    at model.PokemonSchema.methods.findSimilarType (/Users/oescarabel/Documents/programming/developments/workshop-be-mean/nodejs/mongoose-atomic/schema-method.js:15:15)
    at Object.<anonymous> (/Users/oescarabel/Documents/programming/developments/workshop-be-mean/nodejs/mongoose-atomic/schema-method.js:21:6)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3

```

**Comment by escarabelg** [comment]
Não havia me tocado que quando se usa arrow functions temos de ter cuidado com:
- não aceitam new
- não possui arguments
- this não pode ser mudado
- **this tem o valor onde foi criado e não chamado**

Na aula 08 parte 3/6, explica isso, desculpem a falha( mas bati a cabeça feito louco, sendo que no final da aula explicava kkk, aiai)
